sonar.projectKey=Gestion-de-Eventos
sonar.projectName=Gestión de Eventos
sonar.host.url=http://localhost:9000

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,tests/**

sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info